version: '3.10'

services:
  db:
    image: postgres:15.0-alpine
    env_file:
      - ./docker.env
    volumes:
      - /var/lib/postgresql/data/
    networks:
      - digestservice

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - digestservice
    command: >
      bash -c "python3 src/main.py --host 0.0.0.0 --port 8000"

networks:
  digestservice:

