version: '3.10'

services:
  # Контейнер с базой данных Postgres
  db:
    image: postgres:15.0-alpine
    env_file:
      - ./.env
    volumes:
      - /var/lib/postgresql/data/


  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    command: >
      bash -c "python3 src/main.py"

volumes:
  db_value: